Доработать функциональность по ТЗ спринта 10:
создать каркас Spring Boot приложения.
iGladkikh/java-filmorate pull request #5
Opened 2024-05-20 13:17 UTC by iGladkikh

2024-05-20 17:09 UTC, Yang-Pi requested changes

2024-05-20 17:09 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/Controller.java
> +    long getNextId(Map<Long, T> entities) {
protected лучше

2024-05-20 17:09 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final String FILM_NOT_FOUND_ERROR = "Фильм не найден";
В целом неплохая идея, но тут две опции
1) либо не использовать константы
2) либо использовать в конструкторе исключения DuplicateElementException (только тогда нужно переименоват на DuplicateFiltException)

те лучше не перегуржать класс контроллера немного лишней информацией

2024-05-20 17:09 UTC, Yang-Pi commented on src/main/resources/application.properties
> +logging.level.ru.yandex.practicum.filmorate=ERROR
INFO лучше, потому что логгировать стоит не только ошибки, но и в целом информацию о поведении системы

2024-05-20 17:09 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/Controller.java
> +abstract class Controller<T> {
Хорошая идея унифицировать коннекторы

2024-05-21 05:48 UTC, iGladkikh commented on src/main/java/ru/yandex/practicum/filmorate/controller/Controller.java
> +    long getNextId(Map<Long, T> entities) {
Исправлено. Спасибо!

2024-05-21 06:02 UTC, iGladkikh commented on src/main/resources/application.properties
> +logging.level.ru.yandex.practicum.filmorate=ERROR
Исправлено. Спасибо!

2024-05-22 05:15 UTC, Yang-Pi approved these changes

2024-05-22 05:53 UTC, merged